# Generated by Django 2.2.5 on 2019-09-18 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LOGINAPP', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='counted',
            new_name='imagecount',
        ),
    ]
